### ISSUE TITLE
Add support for XAG

### ISSUE THREAD

**Issue by xagfans** [ripplefox/ripplewallet#7]
XAG is the folk of the Ripple. Although it is quite easy to switch the user defined network. However, it is more convenient if the wallet have a separate network option besides the "Test net"

XAG have a lot of users, it will be a good chance for them to use Foxlet as their main wallet.

**Comment by ripplefox** [comment]
interesting. however, we currently busy working on the new design of the federation protocol. we do not have too much time to add another type of network.

**Comment by xagfans** [comment]
That is ok. We can create a pr then.

XAG fork network is quite stable now. It is more than a year since its launch. And a technology is not a scam. Soon, we will also have gateways on Ripple

**Comment by xagfans** [comment]
we also suggest adding another field like 'network' when you design the federation protocol. so that the gateway could know which network the payment going to happen.

If so, our gateways will use foxlet as the client. We will open gateways in Korea, Japan, Vietnam.

**Comment by ripplefox** [comment]
Seems you are working hard and the pr is ready so soon. However, we want to test it before the release. Would it possible you donate some XAG to our hotwallet rLSnkKvMfPD9abLoQFxQJMYyZqJcsqkL3o. You could find it on our ripple.txt file.

**Comment by xagfans** [comment]
Sure. We will do some giveaway for those ones who do contribution to the whole community. 

As I know, there will be a build challenge competition in the coming months. You can also join and win more.
