### ISSUE TITLE
Add xagfans gateway to gateway list

### ISSUE THREAD

**Issue by xagfans** [ripplefox/ripplewallet#9]
Would you please add the gateway to the list, so people could add the gateway just by one click.

Issuer: rpG9E7B3ocgaKqG7vmrsu3jmGwex8W4xAG
Currency: XAG

**Comment by ripplefox** [comment]
It is great to see a new gateway. However, xag gateway is not active enough to be one in the list. I checked your issuer address, the trustline is less than 100, and the trade volume is few. 

Would you please make it more popular first?

**Comment by xagfans** [comment]
The gateway is quite popular. It is almost 1000 trustlines now, and soon it will become more. I do believe add the xag gateway would increase the user number a lot.

**Comment by ripplefox** [comment]
Amazing, you are working so hard. we will include your pr in next release.
